version: "3.5"

services:

  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=jogo_da_memoria_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 54954:54954
