version: "3.7"

services:
  postgres:
    container_name: postgres
    image: bitnami/postgresql:latest
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=jogo_da_memoria
    volumes:
      - jogo_da_memoria_pg_data:/bitnami/postgresql

volumes:
  jogo_da_memoria_pg_data:
